name: CI

on:
  # workflow dispatch with customized inputs: repo_url, commit_hash, event_name
  workflow_dispatch:
    inputs:
      run_id:
        description: "Run ID"
        required: true
      machine:
        description: "Machine type"
        required: true
        default: "macos-latest"
      repo_url:
        description: "Repository URL"
        required: true
      commit_hash:
        description: "Commit hash"
        required: true
      event_name:
        description: "Event name"
        required: true
      pull_credential:
        description: "Pull credential"
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ github.event.inputs.machine }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      - name: Install Act
        run: |
          brew install act

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          path: repo
          repository: ${{ github.event.inputs.repo_url }}
          token: ${{ github.event.inputs.pull_credential }}
          ref: ${{ github.event.inputs.commit_hash }}

      - name: Start workflow
        run: |
          cd repo
          act -P ${{ github.event.inputs.machine }}=-self-hosted

      - name: Post workflow run
        run: |
          echo "finished workflow run"
